spring.application.name=alessio-wms

spring.datasource.url=jdbc:postgresql://localhost:5432/alessio_wms_db
spring.datasource.username=louisalessio
spring.datasource.password=

#postgresql driver
spring.datasource.driver-class-name=org.postgresql.Driver

#temp configuration for developing with hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect